import AddProject from "@/components/AddProject";
import { addProject } from "@/components/projectData";
import { useState } from "react";
import Head from "next/head";
import { Fragment } from "react";
import Button from "@/components/button";
import Table from "@/components/table";
import { ToastContainer } from "react-toastify";
export default function HomePage() {
  const [popup, setPopup] = useState(false);
  const [isTrue, setIsTrue] = useState(false);
  // const [projectData, setProjectData] = useState([]);

  const handleOpen = () => {
    setPopup(true);
  };

  const handleClose = () => {
    setPopup(false);
  };

  const btn = {
    display: "flex",
    margin: "auto",
  };

  const handleIsTrue = () => {
    setIsTrue(true);
  };

  // const addProjectData = (data) => {
  //   setProjectData([...projectData, data]);
  // };

  const addProjectData = (data) => {
    addProject(data);
  };

  return (
    <Fragment>
      <Head>
        <title>Add Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          width: "100%",
          height: "100vh",
          display: "flex",
          justifyContent: "center",
        }}
      >
        {popup && (
          <AddProject
            handleClose={handleClose}
            handleIsTrue={handleIsTrue}
            addProjectData={addProjectData}
          />
        )}
        {!isTrue ? (
          <Button
            text="Start Adding Projects"
            onClick={handleOpen}
            style={btn}
          />
        ) : (
          <Table handleIsTrue={handleIsTrue} />
        )}
      </div>
      <ToastContainer position="top-right" autoClose={3000} />
    </Fragment>
  );
}
